// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkeaseAPI.Data;

#nullable disable

namespace WorkeaseAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260608144318_InitialMigrations")]
    partial class InitialMigrations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkeaseAPI.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceRecordId"));

                    b.Property<DateTime>("AttendanceRecordCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("AttendanceRecordDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("AttendanceRecordIsPresent")
                        .HasColumnType("bit");

                    b.Property<bool>("AttendanceRecordIsSync")
                        .HasColumnType("bit");

                    b.Property<DateTime>("AttendanceRecordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("AttendanceRecordedByUserId")
                        .HasColumnType("int");

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.HasKey("AttendanceRecordId");

                    b.HasIndex("AttendanceRecordedByUserId");

                    b.HasIndex("ChildId", "AttendanceRecordDate");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Center", b =>
                {
                    b.Property<int>("CenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CenterId"));

                    b.Property<string>("CenterLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CenterId");

                    b.ToTable("Centers");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Child", b =>
                {
                    b.Property<int>("ChildId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChildId"));

                    b.Property<int>("CenterId")
                        .HasColumnType("int");

                    b.Property<string>("ChildAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChildBirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ChildEnrolledDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ChildFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChildGender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ChildIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ChildLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ChildUpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("GuardianId")
                        .HasColumnType("int");

                    b.HasKey("ChildId");

                    b.HasIndex("CenterId");

                    b.HasIndex("GuardianId");

                    b.ToTable("Children");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.FeeRecord", b =>
                {
                    b.Property<int>("FeeRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeeRecordId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeRecordCarryOver")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FeeRecordCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeeRecordDueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("FeeRecordIsOverdue")
                        .HasColumnType("bit");

                    b.Property<bool>("FeeRecordIsPaid")
                        .HasColumnType("bit");

                    b.Property<int>("FeeRecordMonth")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeRecordMonthlyAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("FeeRecordPaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FeeRecordReceiptNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("FeeRecordTotalAmount")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("FeeRecordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("FeeRecordYear")
                        .HasColumnType("int");

                    b.Property<int>("FeeRecordedByUserId")
                        .HasColumnType("int");

                    b.HasKey("FeeRecordId");

                    b.HasIndex("ChildId");

                    b.HasIndex("FeeRecordedByUserId");

                    b.ToTable("FeeRecords");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Growth", b =>
                {
                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<int>("Cognitive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Creative")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("LifeSkills")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Motor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Reading")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Social")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("SpentPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("TotalPoints")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ChildId");

                    b.ToTable("Growths");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.HealthRecord", b =>
                {
                    b.Property<int>("HealthRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HealthRecordId"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<DateTime>("HealthRecordCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HealthRecordDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HealthRecordHeightCm")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HealthRecordIsSync")
                        .HasColumnType("bit");

                    b.Property<string>("HealthRecordNotes")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("HealthRecordUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("HealthRecordWeightKg")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("HealthRecordedByUserId")
                        .HasColumnType("int");

                    b.HasKey("HealthRecordId");

                    b.HasIndex("ChildId");

                    b.HasIndex("HealthRecordedByUserId");

                    b.ToTable("HealthRecords");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<int?>("CdwCenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GeneratedByUserId")
                        .HasColumnType("int");

                    b.Property<byte[]>("ReportFileData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ReportFormat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportMonth")
                        .HasColumnType("int");

                    b.Property<string>("ReportTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ReportYear")
                        .HasColumnType("int");

                    b.HasKey("ReportId");

                    b.HasIndex("CdwCenterId");

                    b.HasIndex("GeneratedByUserId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.SyncLog", b =>
                {
                    b.Property<int>("SyncLogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SyncLogId"));

                    b.Property<int>("SyncLogFailedSyncedCounts")
                        .HasColumnType("int");

                    b.Property<int>("SyncLogRecordFeeRecordsSynced")
                        .HasColumnType("int");

                    b.Property<int>("SyncLogRecordHealthRecordsSynced")
                        .HasColumnType("int");

                    b.Property<int>("SyncLogUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("SyncLoggedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("SyncLogId");

                    b.ToTable("SyncLogs");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<int?>("CenterId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UserCreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserHashPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("UserIsActive")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UserUpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserId");

                    b.HasIndex("CenterId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.AttendanceRecord", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.User", "AttendanceRecordedByUser")
                        .WithMany()
                        .HasForeignKey("AttendanceRecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkeaseAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AttendanceRecordedByUser");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Child", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("WorkeaseAPI.Models.User", "Guardian")
                        .WithMany()
                        .HasForeignKey("GuardianId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Center");

                    b.Navigation("Guardian");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.FeeRecord", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkeaseAPI.Models.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("FeeRecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Growth", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Child", "Child")
                        .WithOne()
                        .HasForeignKey("WorkeaseAPI.Models.Growth", "ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Child");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.HealthRecord", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Child", "Child")
                        .WithMany()
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WorkeaseAPI.Models.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("HealthRecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("RecordedByUser");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.Report", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CdwCenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WorkeaseAPI.Models.User", "GeneratedByUser")
                        .WithMany()
                        .HasForeignKey("GeneratedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Center");

                    b.Navigation("GeneratedByUser");
                });

            modelBuilder.Entity("WorkeaseAPI.Models.User", b =>
                {
                    b.HasOne("WorkeaseAPI.Models.Center", "Center")
                        .WithMany()
                        .HasForeignKey("CenterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Center");
                });
#pragma warning restore 612, 618
        }
    }
}
